// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {backend} from '../models';

export function ConnectDevice(arg1:string,arg2:number):Promise<main.APIResponse>;

export function DisconnectDevice():Promise<void>;

export function EnumDevices():Promise<main.APIResponse>;

export function GetConfigPath():Promise<string>;

export function LoadLocalMotors():Promise<void>;

export function ManualAddMotor(arg1:backend.MotorConfig):Promise<main.APIResponse>;

export function MotorEnable(arg1:number,arg2:boolean):Promise<main.APIResponse>;

export function MotorMoveRelative(arg1:number,arg2:number):Promise<main.APIResponse>;

export function MotorStop(arg1:number):Promise<main.APIResponse>;

export function ResetPosition(arg1:number):Promise<main.APIResponse>;

export function SaveMotorsToLocal():Promise<void>;

export function SearchMotors():Promise<main.APIResponse>;
