// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';
import {context} from '../models';
import {main} from '../models';

export function APIUpdate():Promise<backend.GitHubRelease>;

export function AutoMoveMotor(arg1:context.Context,arg2:string,arg3:string,arg4:number):Promise<void>;

export function ConnectDevice(arg1:string,arg2:number):Promise<main.APIResponse>;

export function DeleteMotor(arg1:number):Promise<main.APIResponse>;

export function DisconnectDevice():Promise<void>;

export function EditMotor(arg1:number,arg2:backend.MotorConfig):Promise<main.APIResponse>;

export function EnumDevices():Promise<main.APIResponse>;

export function GetCachedRelease():Promise<backend.GitHubRelease>;

export function GetConfigPath():Promise<string>;

export function LoadLocalMotors():Promise<void>;

export function ManualAddMotor():Promise<main.APIResponse>;

export function MotorEnable(arg1:number,arg2:boolean):Promise<main.APIResponse>;

export function MotorMoveRelative(arg1:number,arg2:number):Promise<main.APIResponse>;

export function MotorStop(arg1:number):Promise<main.APIResponse>;

export function ReadFile():Promise<string>;

export function ResetPosition(arg1:number):Promise<main.APIResponse>;

export function SaveMotorsToLocal():Promise<void>;

export function SearchMotors():Promise<main.APIResponse>;

export function StartAutomation(arg1:string):Promise<boolean>;

export function StopAutomation():Promise<void>;

export function WriteFile(arg1:string):Promise<void>;
