// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectDevice(arg1, arg2) {
  return window['go']['main']['App']['ConnectDevice'](arg1, arg2);
}

export function DisconnectDevice() {
  return window['go']['main']['App']['DisconnectDevice']();
}

export function EnumDevices() {
  return window['go']['main']['App']['EnumDevices']();
}

export function GetConfigPath() {
  return window['go']['main']['App']['GetConfigPath']();
}

export function LoadLocalMotors() {
  return window['go']['main']['App']['LoadLocalMotors']();
}

export function MotorEnable(arg1, arg2) {
  return window['go']['main']['App']['MotorEnable'](arg1, arg2);
}

export function MotorMoveRelative(arg1, arg2) {
  return window['go']['main']['App']['MotorMoveRelative'](arg1, arg2);
}

export function MotorStop(arg1) {
  return window['go']['main']['App']['MotorStop'](arg1);
}

export function SaveMotorsToLocal() {
  return window['go']['main']['App']['SaveMotorsToLocal']();
}

export function SearchMotors() {
  return window['go']['main']['App']['SearchMotors']();
}
