// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function APIUpdate() {
  return window['go']['main']['App']['APIUpdate']();
}

export function AutoMoveMotor(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AutoMoveMotor'](arg1, arg2, arg3, arg4);
}

export function ConnectDevice(arg1, arg2) {
  return window['go']['main']['App']['ConnectDevice'](arg1, arg2);
}

export function DeleteMotor(arg1) {
  return window['go']['main']['App']['DeleteMotor'](arg1);
}

export function DisconnectDevice() {
  return window['go']['main']['App']['DisconnectDevice']();
}

export function EditMotor(arg1, arg2) {
  return window['go']['main']['App']['EditMotor'](arg1, arg2);
}

export function EnumDevices() {
  return window['go']['main']['App']['EnumDevices']();
}

export function GetCachedRelease() {
  return window['go']['main']['App']['GetCachedRelease']();
}

export function GetConfigPath() {
  return window['go']['main']['App']['GetConfigPath']();
}

export function LoadLocalMotors() {
  return window['go']['main']['App']['LoadLocalMotors']();
}

export function ManualAddMotor() {
  return window['go']['main']['App']['ManualAddMotor']();
}

export function MotorEnable(arg1, arg2) {
  return window['go']['main']['App']['MotorEnable'](arg1, arg2);
}

export function MotorMoveRelative(arg1, arg2) {
  return window['go']['main']['App']['MotorMoveRelative'](arg1, arg2);
}

export function MotorStop(arg1) {
  return window['go']['main']['App']['MotorStop'](arg1);
}

export function ReadFile() {
  return window['go']['main']['App']['ReadFile']();
}

export function ResetPosition(arg1) {
  return window['go']['main']['App']['ResetPosition'](arg1);
}

export function SaveMotorsToLocal() {
  return window['go']['main']['App']['SaveMotorsToLocal']();
}

export function SearchMotors() {
  return window['go']['main']['App']['SearchMotors']();
}

export function StartAutomation(arg1) {
  return window['go']['main']['App']['StartAutomation'](arg1);
}

export function StopAutomation() {
  return window['go']['main']['App']['StopAutomation']();
}

export function WriteFile(arg1) {
  return window['go']['main']['App']['WriteFile'](arg1);
}
